config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|pt-BR|es|fr/ do
    get "errors/not_found"
    get "errors/internal_server_error"

    root to: "home#index"
    get "home/index"

    get "map", to: "home#map"
    get "landing", to: "about#landing"
    get "about", to: "about#index"
    get "who_we_are", to: "about#who_we_are"
    get "manual", to: "about#manual"
    get "license", to: "about#license"
    get "thank_you_notes", to: "about#thank_you_notes"
    get "connect", to: "connect#index"
    get "dashboard", to: "dashboard#index"
    get "privacy_policy", to: "about#privacy_policy"

    get "coordinates", to: "locations#coordinates"
    get "countries", to: "locations#countries"
    put "/practices/:id/like", to: "practices#like", as: "like"

    resources :practices
    resources :acknowledges
    resources :evaluates
    resources :characterises
    resources :what_you_dos
    resources :comments

    resources :practices do
      resources :acknowledges
      resources :evaluates
      resources :characterises
      resources :what_you_dos
      resources :medias
      resources :documents
      resources :comments
      get "/gallery" => "medias#gallery"
    end

    resources :locations do
      get "/gallery" => "medias#gallery"
      resources :practices
      resources :medias
      resources :documents
    end

    devise_for :accounts, controllers: {
      registrations: "accounts/registrations",
      sessions: "accounts/sessions",
      confirmations: "accounts/confirmations"
    }

    resources :accounts do
      resources :locations
      resources :practices
    end

    post "login", to: "authentication#login"
    post "signup", to: "authentication#signup"
    post "validate_jwt_token", to: "authentication#validate_jwt_token"

    match "/404", to: "errors#not_found", via: :all
    match "/500", to: "errors#internal_server_error", via: :all
    match "/422", to: "errors#unprocessable_entity", via: :all
  end
end

app/models/practice.rb
# frozen_string_literal: true

class Practice < ApplicationRecord
  paginates_per 10

  scope :by_name, -> (name) { where("practices.name ILIKE ?", "%#{name}%") }
  scope :by_food_system_components_addressed, -> (food_system_components_addressed) { joins(:characterise).where("characterises.food_system_components_addressed ILIKE ?", "%#{food_system_components_addressed}%") }
  scope :by_agroecology_principles_addressed, -> (agroecology_principles_addressed) { joins(:characterise).where("characterises.agroecology_principles_addressed ILIKE ?", "%#{agroecology_principles_addressed}%") }
  scope :by_where_it_is_realized, -> (where_it_is_realized) { joins(:what_you_do).where("what_you_dos.where_it_is_realized ILIKE ?", "%#{where_it_is_realized}%") }
  scope :by_knowledge_source, -> (knowledge_source) { joins(:acknowledge).where("acknowledges.knowledge_source ILIKE ?", "%#{knowledge_source}%") }
  scope :by_farm_and_farming_system, -> (farm_and_farming_system) { joins(:location).where("locations.farm_and_farming_system ILIKE ?", "%#{farm_and_farming_system}%") }
  scope :by_farm_and_farming_system_complement, -> (farm_and_farming_system_complement) { joins(:location).where("locations.farm_and_farming_system_complement ILIKE ?", "%#{farm_and_farming_system_complement}%") }
  scope :by_country, -> (country) { joins(:location).where("locations.country ILIKE ?", "%#{country}%") }
  scope :by_continent, -> (continent) { joins(:location).where("locations.continent ILIKE ?", "%#{continent}%") }
  scope :by_substitution_of_less_ecological_alternative, -> (substitution_of_less_ecological_alternative) { joins(:what_you_do).where("what_you_dos.substitution_of_less_ecological_alternative ILIKE ?", "%#{substitution_of_less_ecological_alternative}%") }
  scope :by_does_it_help_restore_land, -> (does_it_help_restore_land) { joins(:evaluate).where("evaluates.does_it_help_restore_land ILIKE ?", "%#{does_it_help_restore_land}%") }
  scope :by_does_it_work_in_degraded_environments, -> (does_it_work_in_degraded_environments) { joins(:evaluate).where("evaluates.does_it_work_in_degraded_environments ILIKE ?", "%#{does_it_work_in_degraded_environments}%") }
  scope :by_knowledge_and_skills_required_for_practice, -> (knowledge_and_skills_required_for_practice) { joins(:evaluate).where("evaluates.knowledge_and_skills_required_for_practice ILIKE ?", "%#{knowledge_and_skills_required_for_practice}%") }

  has_one :what_you_do, dependent: :destroy
  has_one :characterise, dependent: :destroy
  has_one :evaluate, dependent: :destroy
  has_one :acknowledge, dependent: :destroy

  has_many :medias, dependent: :destroy
  has_many :documents, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :photo do |attachable|
    attachable.variant :original, resize_to_limit: [1920, nil]
    attachable.variant :medium, resize_to_limit: [600, nil]
    attachable.variant :thumb, resize_to_limit: [300, nil]
  end

  belongs_to :account
  belongs_to :location

  validates :name, presence: true
  validates_length_of :name, minimum: 2
  validates_length_of :name, maximum: 255
  validate :acceptable_photo

  extend FriendlyId
  friendly_id :name, use: :slugged

  before_save do
    self.name = name.strip
  end

  protected
    def should_generate_new_friendly_id?
      name_changed?
    end

    def acceptable_photo
      return unless photo.attached?

      unless photo.blob.byte_size <= 16.megabyte
        errors.add(:photo, "Size Limit is 16 Mb")
      end

      acceptable_types = ["image/jpeg", "image/png", "image/gif", "image/webp"]
      unless acceptable_types.include?(photo.content_type)
        errors.add(:photo, "must be a JPEG, PNG, GIF or WebP")
      end
    end

    require "csv"
    def self.to_csv
      cols = column_names.map(&:clone)

      cols.delete("slug")
      cols.delete("account_id")
      cols.delete("location_id")
      cols.delete("created_at")
      cols.delete("updated_at")

      cols.push("description")
      cols.push("agroecology_principles_addressed")
      cols.push("food_system_components_addressed")
      cols.push("location_name")
      cols.push("created_at")
      cols.push("updated_at")

      CSV.generate do |csv|
        csv << cols

        cols.delete("description")
        cols.delete("agroecology_principles_addressed")
        cols.delete("food_system_components_addressed")
        cols.delete("location_name")
        cols.delete("created_at")
        cols.delete("updated_at")

        Practice.all.joins(:location, :what_you_do, :characterise).order(:id).each do |practice|
          vals = practice.attributes.values_at(*cols).map(&:clone)
          vals.push(practice.what_you_do.attributes["summary_description_of_agroecological_practice"])
          vals.push(practice.characterise.attributes["agroecology_principles_addressed"])
          vals.push(practice.characterise.attributes["food_system_components_addressed"])
          vals.push(practice.location.attributes["name"])
          vals.push(practice.attributes["created_at"])
          vals.push(practice.attributes["updated_at"])
          csv << vals
        end
      end
    end
end

app/controllers/practices_controller.rb
# frozen_string_literal: true

class PracticesController < ApplicationController
  skip_before_action :authenticate, except: %i[index, show], if: -> { request.format.json? }
  before_action :authenticate_account!, only: %i[new edit update destroy], if: -> { !request.format.json? }

  before_action lambda { check_owner Practice.friendly.find(params[:id]).account_id }, only: %i[edit update destroy]
  before_action :set_practice, only: %i[show edit update destroy]
  before_action :load_locations, except: %i[index show]
  before_action :load_location
  before_action :load_account
  before_action :load_principles
  before_action :load_system_options
  before_action :load_locations, only: %i[new]
  before_action :load_comments, only: %i[show]
  before_action :load_total

  # GET /practices
  # GET /practices.json
  def index
    @practices = if params[:filter]
      filter
    else
      if request.format == :html
        all
      elsif request.format == :csv
        respond_to do |format|
          format.csv { send_data Practice.to_csv, filename: "practices-#{DateTime.now.strftime("%Y-%m-%d")}.csv" }
        end
      else
        if params[:page]
          Practice.all.includes(:account, :location).order("updated_at DESC").with_attached_photo.page(params[:page])
        else
          Practice.all.includes(:account, :location).order("updated_at DESC").with_attached_photo
        end
      end
    end
  end

  def all
    @practices = if params[:location_id]
      Practice.where(location_id: @location.id).sort_by(&:updated_at).reverse
    elsif params[:account_id]
      Practice.where(account_id: @account.id).sort_by(&:updated_at).reverse
    else
      Practice.includes(:account, :location).with_attached_photo.order("updated_at DESC").page(params[:page])
    end
  end
  def filter
    @practices = Practice.unscoped
    @practices = @practices.by_name(params[:name]) unless params[:name].blank?
    @practices = @practices.by_food_system_components_addressed(params[:components]) unless params[:components].blank?
    @practices = @practices.by_agroecology_principles_addressed(params[:principles]) unless params[:principles].blank?
    @practices = @practices.by_farm_and_farming_system(params[:system_functions]) unless params[:system_functions].blank?
    @practices = @practices.by_farm_and_farming_system_complement(params[:system_components]) unless params[:system_components].blank?
    @practices = @practices.by_country(params[:country]) unless params[:country].blank?
    @practices = @practices.by_continent(params[:continent]) unless params[:continent].blank?
    @practices = @practices.with_attached_photo
    @total = @practices.count
    if request.format == :html
      @practices = @practices.order("practices.updated_at DESC").page(params[:page])
    else
      @practices = @practices.order("practices.updated_at DESC")
    end
  end

  # GET /practices/1
  # GET /practices/1.json
  def show
    @comment = Comment.new
  end

  # GET /practices/new
  def new
    @practice = Practice.new
  end

  # GET /practices/1/edit
  def edit; end

  # POST /practices
  # POST /practices.json
  def create
    @practice = Practice.new(practice_params)

    if request.format.json?
      if params[:base64Image]
        base64Image = params[:base64Image]
        decoded_data = Base64.decode64(base64Image)
        @practice.photo = {
                            io: StringIO.new(decoded_data),
                            content_type: "image/jpeg",
                            filename: "image.jpg"
                          }
      end

      @practice.account_id = authenticate.id
    else
      @practice.account_id = current_account.id unless current_account.admin?
    end

    respond_to do |format|
      if @practice.save

        summary_description = params[:summaryDescription] || ""
        where_it_is_realized = params[:whereItIsRealized] || ""

        @what_you_do = WhatYouDo.new(practice_id: @practice.id,
                                     summary_description_of_agroecological_practice: summary_description,
                                     where_it_is_realized:).save!
        @characterise = Characterise.new(practice_id: @practice.id).save!
        @evaluate = Evaluate.new(practice_id: @practice.id).save!
        @acknowledge = Acknowledge.new(practice_id: @practice.id).save!

        format.html { redirect_to new_practice_what_you_do_path(@practice), notice: "Practice Registered" }
        format.json { render json: { message: "created" }, status: :created }
      else
        format.html { render :new }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /practices/1
  # PATCH/PUT /practices/1.json
  def update
    respond_to do |format|
      if @practice.update(practice_params)
        format.html { redirect_to @practice, notice: "A Practice has been Updated" }
        format.json { render :show, status: :ok, location: @practice }
      else
        format.html { render :edit }
        format.json { render json: @practice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /practices/1
  # DELETE /practices/1.json
  def destroy
    @practice.destroy
    respond_to do |format|
      format.html { redirect_to practices_url, notice: "Practice has been Removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_practice
      @practice = Practice.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def practice_params
      if request.format.json?
        params.require(:practice).permit(:name, :photo, :slug, :location_id, :account_id, :base64Image)
      else
        params.require(:practice).permit(:name, :photo, :slug, :location_id, :account_id)
      end
    end

    def load_location
      @location = Location.friendly.find(params[:location_id]) if params[:location_id]
    end

    def load_account
      @account = Account.friendly.find(params[:account_id]) if params[:account_id]
    end

    def load_comments
      @practice_id = Practice.friendly.find(params[:id]).id
      @comments = Comment.where(practice_id: @practice_id).page(params[:page])
    end
    def load_total
      @total = Practice.count
    end
end

app/views/practices/_comment.html.erb
<%= form_for([@practice, comment], html: { multipart: true }) do |f| %>
  <div class="col-xs-4" style="padding-bottom: 25px">
    <%= f.text_area :comment, rows: 4, class: "form-control", placeholder: t(:comment) %>
    <%= f.submit t(:submit_comment), class: "btn btn-info", style: "float: right; margin-top: 8px; margin-bottom: 8px;" %>
  </div>
<% end %>

app/views/practices/_comments.html.erb
<div class="comment-box">
  <table id="dataTable-agroecologia" class="table table-striped table-bordered" width="100%" cellspacing="0">
    <thead><tr><th style="display: none;"></th></tr></thead>
    <tbody>
    <% comments.each do |comment| %>
      <tr>
        <td style="width: 9%; padding-bottom: 14px; padding-top: 24px; text-align: justify;">
          <%= simple_format(comment.comment) %>
          <div class="comment-footer">By <%= link_to comment.account.name, account_path(comment.account) %> on <%= comment.created_at %></div>
          <% if account_signed_in? %>
            <% if current_account.admin? or comment.account.id == current_account.id %>
              <div style="text-align: right;">
                <%= link_to t(:destroy), comment_path(comment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :style => 'color: #ff0000ff; font-size: 12px; font-weight: bold;' %>
              </div>
            <% end %>
          <% end %>
        </td>
      </tr>
      <div>

      </div>
    <% end %>
    </tbody>
  </table>
  <%= paginate comments %>
</div>

app/views/practices/_locations.html.erb
<% title t(:locations) %>

<div class="tip">Choose the location to add the Practice</div>
<br>

<% if @locations.empty? %>
  <br>
  <h2><%= t(:no_data_has_been_registered_so_far) %> <%= link_to t(:register_new_location), new_location_path if account_signed_in? %> first</h2>
<% else %>
  <div class="row">
    <% @locations.each do |location| %>
      <div class="col-sm-6" style="cursor: pointer;" onclick="window.location='<%= new_location_practice_path(location) %>';">
        <div class="card">
          <br>
          <div  class="card-img-top thumbnail"><%= link_to photo_thumb(location), new_location_practice_path(location), alt: location.name, title: location.name %></div>
          <div class="card-body"  style="min-height: 100px;">
            <h3 class="card-title"><%= link_to location.name.truncate(40), new_location_practice_path(location) %></h3>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>
<% end %>

app/views/practices/edit.html.erb
<% title t(:register_new_practice) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to @practice.name.truncate(25), practices_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:edit)}", edit_practice_path(@practice), :class => "nav-link active" %>
  </li>
</ul>

<br>

<% if !@location.blank? %>
  <%= render 'form', practice: @practice %>
<% else %>
  <br>
  <h3>Nenhum Location Cadastrado. Deseja <%= link_to "Cadastrar um Location Agora?", new_location_url %></h3>
<% end %>

app/views/practices/index.html.erb
<% title t(:practices) %>

<div class="link-action">
  <%= link_to (bootstrap_icon "clipboard-check") + " " + t(:register_new_practice), new_practice_path, :class => "btn btn-info" %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to @location.name.truncate(25), location_path(@location), title: @location.name, :class => "nav-link" %>
    </li>
  <% end %>

  <li class="nav-item">
    <% if params[:location_id] %>
      <%= link_to t(:practices) + " (#{@practices.count})", "#", :class => "nav-link active" %>
    <% else %>
      <%= link_to t(:practices) + " (#{@practices.count} #{t(:of)} #{@total})", "#", :class => "nav-link active" %>
    <% end %>
  </li>


  <% if params[:location_id] %>
    <li class="nav-item">
      <%= link_to t(:gallery) + " (#{@location.medias.count})", location_gallery_path(@location.id), :class => "nav-link" %>
    </li>
  <% end %>
</ul>

<div style="margin-top: 8px; margin-bottom: 8px; text-align: left">
  <%= text_field_tag "search", {}, class: "btn dropdown-toggle btn-default search", placeholder: t(:search) %>
  <%= link_to (bootstrap_icon "search"), "#", id: 'searchButton', onclick: 'filter()' %>
  <br>
  <span style="font-size: 14px;"><a href="#" onclick="showAdvancedFilters()"><%= t(:show_more_filters) %></a></span>
  <div id="more-filter">
    <%= select_tag "system_functions", options_from_collection_for_select(@system_functions_options, :last, :first, params[:system_functions] ? params[:system_functions] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_farm_functions) %>
    <%= select_tag "system_components", options_from_collection_for_select(@system_components_options, :last, :first, params[:system_components] ? params[:system_components] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_farm_components) %>
    <%= select_tag "components", options_from_collection_for_select(@food_system_components_addressed_options, :last, :first, params[:components] ? params[:components] : ''), class: "selectpicker", "data-live-search": true, :include_blank => t(:filter_by_system_component)  %>
    <%= select_tag "principles", options_from_collection_for_select(@agroecology_principles_addressed_options, :last, :first, params[:principles] ? params[:principles] : ''), class: "selectpicker", "data-live-search": true, :include_blank => t(:filter_by_agroecology_principle) %>
    <%= country_select("country", "country", { selected: params[:country] ? params[:country] : '', :include_blank => t(:Filter_by_country) }, { class: "selectpicker", "data-live-search": true}) %>
    <%= select_tag "continent", options_from_collection_for_select(@continent_options, :last, :first, params[:continent] ? params[:continent] : ''), class: "selectpicker",  "data-live-search": true, :include_blank => t(:filter_by_continent) %>
    <div style="padding-top: 10px; padding-bottom: 10px; align-content: center; text-align: center; font-size: 21px">
      <%= link_to (bootstrap_icon "search", width: 16, style: "margin-bottom: 3px") + " " + t(:filter), "#", onclick: 'filter()', class: "btn btn-warning btn-lg" %>
      <%= link_to " " + t(:clear_filters), locations_path, class: "btn btn-info btn-lg" %>
    </div>
  </div>
</div>

<% if @practices.empty? %>
  <br>
  <h2>
    <%= t(:no_data_has_been_registered_so_far) %>
    <% if params[:location_id] %>
      <% if account_signed_in? %>
        <% if current_account.admin? or current_account.id == @location.account.id %>
          <%= link_to t(:add_a_practice), new_location_practice_path(@location) unless @location.blank? %>
        <% end %>
      <% end %>
    <% end %>
  </h2>
<% else %>
  <div class="row">
    <% @practices.each do |practice| %>
      <div class="col-sm-6" style="cursor: pointer;" onclick="window.location='<%= location_practice_path(practice.location, practice) %>';">
        <div class="card" style="min-height: 340px;">
          <br>
          <div class="card-img-top thumbnail"><%= link_to photo_thumb(practice, practice.name, true), practice_path(practice), alt: practice.location.name, title: practice.location.name %></div>
          <div class="card-body">
            <h4 class="card-title"><%= link_to practice.name.truncate(40), location_practice_path(practice.location, practice) %></h4>
            <p class="card-text text-box"><b><%= t(:location) %></b><br> <%= link_to practice.location.name.truncate(40), location_path(practice.location) %></p>
          </div>
        </div>
        <br>
      </div>
    <% end %>
  </div>

  <% if not params[:account_id] and not params[:location_id] %>
    <div>
      <%= paginate @practices %>
    </div>
  <% end %>
<% end %>

<script>
    const controller = 'practices';

    $(document).ready(function () {
        <% if params[:filter].blank? or params[:name] %>
        $("#more-filter").hide();
        $("#searchButton").show();
        <% else %>
        $("#searchButton").hide();
        <% end %>
    });

    $("#search").on('keyup', function (event) {
        if (event.keyCode === 13) {
            filter("search");
        }
    });

    function filter() {
        var name = $("#search").val();
        var system_functions = $("#system_functions :selected").val();
        var system_components = $("#system_components :selected").val();
        var components = $("#components :selected").val();
        var principles = $("#principles :selected").val();
        var country = $("#country_country :selected").val();
        var continent = $("#continent :selected").val();

        var filter = "?filter=true"
        filter += name ? "&name=" + name : "";
        filter += system_functions ? "&system_functions=" + system_functions : "";
        filter += system_components ? "&system_components=" + system_components : "";
        filter += components ? "&components=" + components : "";
        filter += principles ? "&principles=" + principles : "";
        filter += country ? "&country=" + country : "";
        filter += continent ? "&continent=" + continent : "";
        var url = "/" + controller + "/" + filter;

        var lang = '<%= params[:locale] ? params[:locale] : 'en' %>'

        if (url != '/' + controller + '/?filter=true') {
            window.location.href =  '/' + lang + url;
        }
        else {
            window.location.href = '/' + lang + '/' + controller;
        }
    }

    function showAdvancedFilters() {
        $("#more-filter").is(":visible") ? $("#more-filter").hide() : $("#more-filter").show();
        $("#more-filter").is(":visible") ? $("#searchButton").hide() : $("#searchButton").show();
    }
</script>

app/views/practices/new.html.erb
<% title t(:what_you_do) %>

<div class="link-action"></div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to t(:practices), practices_path, :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:practice), practices_path, :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:evaluate), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:acknowledge), "#", :class => "nav-link", :style => "color: #979797 !important" %>
  </li>
</ul>

<br>
<% if params[:location_id] or params[:action] == "create" %>
  <%= render 'form', practice: @practice %>
<% end %>

<% if params[:location_id].blank? and params[:action] == "new" %>
  <%= render 'locations' %>
<% end %>

app/views/practices/show.html.erb
<% title @practice.location.name %>

<div class="link-action">
<% if account_signed_in? %>
  <% if current_account.admin? or current_account.id == @practice.account.id %>
      <%= link_to (bootstrap_icon "file-earmark-image") + " " + t(:send_photo), new_practice_media_path(@practice), :class => "btn btn-warning" %>
      <%= link_to (bootstrap_icon "file-earmark-text") + " " + t(:send_document), new_practice_document_path(@practice), :class => "btn btn-secondary" %>
  <% end %>
<% end %>
</div>

<ul class="nav nav-tabs flex-column flex-xl-row">
  <li class="nav-item">
    <%= link_to truncate(@practice.location.name, length: 12), location_path(@practice.location), title: @practice.location.name,  :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to @practice.name.truncate(18) , practice_path(@practice), :class => "nav-link active" %>
  </li>
  <li class="nav-item">
    <%= link_to t(:what_you_do), practice_what_you_do_path(@practice, @practice.what_you_do), :class => "nav-link" if @practice.what_you_do %>
  </li>
  <li class="nav-item">
    <%= link_to t(:characterise), practice_characterise_path(@practice, @practice.characterise), :class => "nav-link" if @practice.characterise %>
  </li>
  <li class="nav-item">
    <%= link_to t(:evaluate), practice_evaluate_path(@practice, @practice.evaluate), :class => "nav-link" if @practice.evaluate %>
  </li>
  <li class="nav-item">
    <%= link_to t(:acknowledge), practice_acknowledge_path(@practice, @practice.acknowledge), :class => "nav-link" if @practice.acknowledge %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:gallery)} (#{@practice.medias.count})", practice_gallery_path(@practice), :class => "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "#{t(:documents)} (#{@practice.documents.count})", practice_documents_path(@practice), :class => "nav-link" %>
  </li>
</ul>

<br>

<div class="tab-content" style="min-height: 64px;">

  <div class="tab-pane active">
    <div class="thumbnail">
      <%= photo_original(@practice, @practice.name) %>
    </div>

    <br>
    <h1><%= @practice.name.truncate(45) %></h1>
    <br>

    <% if ! @practice.what_you_do.summary_description_of_agroecological_practice.blank? %>
      <%= "<h4>#{t(:summary_description)}</h4>".html_safe  %>
      <div class="text-box"><%= @practice.what_you_do.summary_description_of_agroecological_practice.truncate(512) %></div>
      <br>
    <% end %>

    <%= "<h4>#{t(:location)}</h4>#{link_to @practice.location.name.truncate(40), location_path(@practice.location)}&nbsp;".html_safe if @practice.location.name? %>
    <br><br>
    <div class="practices-box bg-light"><%= "<h4>#{t(:responsible_for_information)}</h4>#{link_to @practice.account.name, account_path(@practice.account)}&nbsp;".html_safe if @practice.account.name? %></div>

    <h4><%= @practice.comments.count.to_s + " " + t(:comments) + "(s)" %>:</h4>
    <% if  account_signed_in? %>
      <div class='comment-box'>
        <%= render 'comment', comment: @comment %>
      </div>
    <% end %>

    <%= "<b>#{link_to t(:sign_in_to_comment), new_account_session_path, :class => 'text-danger'}</b>".html_safe if !account_signed_in? %>
    
    <% if @practice.comments.count > 0 %>
      <%= render 'comments', comments: @comments.order(:updated_at).reverse_order %>
    <% end %>

    <% if account_signed_in? %>
      <% if current_account.admin? or current_account.id == @practice.account.id %>
        <br><hr>
        <div id="practice-footer">
          <div class="form-actions">
            <%= link_to t(:edit), edit_location_practice_path(@practice.location, @practice.id), :class => 'btn btn-success' %>
            <%= link_to t(:destroy), practice_path(@practice), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Você tem Certeza?')) }, :class => 'btn btn-danger' %>
          </div>
        </div>
      <% end %>
    <% end %>

    <br><br>
  </div>
</div>